version: '3'
services:
  db:
    image: mysql:5.7
    container_name: go-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - ./db/data:/var/lib/mysql
    ports:
    - 5506:3306